export const CHECK_DOMAIN_NAME_LOADING = 'CHECK_DOMAIN_NAME_LOADING';
export const CHECK_DOMAIN_NAME_SUCCESS = 'CHECK_DOMAIN_NAME_SUCCESS';
export const CHECK_DOMAIN_NAME_FAILED = 'CHECK_DOMAIN_NAME_FAILED';